FROM openjdk:17-jdk-slim

WORKDIR /app

COPY target/Project-CourseEnrolment-0.0.1-SNAPSHOT.jar /app

EXPOSE 8083

CMD ["java", "-jar", "Project-CourseEnrolment-0.0.1-SNAPSHOT.jar", "--spring.profiles.active=docker"]